### ISSUE TITLE
How to run program separately on each CPU in baremetal?

### ISSUE THREAD

**Issue by cnjsdfcy** [janweinstock/or1kmvp#2]
Hi,

I managed to run the coremark.elf (from or1kiss/sw) on single-core or1kmvp with `system.mem.images` modified in up.cfg as below:
![image](https://user-images.githubusercontent.com/5670527/121026619-e1cb6a00-c7d8-11eb-8251-fa50b1a2b5ad.png)

But, when I tried to run this elf on both two CPUs on SMP2 config, it seems not working and got below logs:
![image](https://user-images.githubusercontent.com/5670527/121028333-52bf5180-c7da-11eb-991d-738d8188995a.png)

How should I modify smp2.cfg to run coremark correctly on each CPU?
Thanks,
Cai Yu

**Comment by janweinstock** [comment]
There are many ways to do this, but I think the easiest way would be to load a second copy of your program into memory at a different offset. Then, point the second processors PC to the entry point of the copied program. It will also be necessary to move the stack of the second processor to a different location, either in your program, or by setting the stack point via config file.

**Comment by cnjsdfcy** [comment]
Thanks for you reply, I will try to make it work.
