### ISSUE TITLE
When cloning the repo there are 3 files that are not checkedout

### ISSUE THREAD

**Issue by chakanp** [janweinstock/or1kmvp#3]
sdcard0.gpt, vmlinux-5.4 and vmlinux-5.4.elf are all not checked out when cloning the repo, when trying to do :
git lfs fetch I get: 
Fetching master
Git LFS: (0 of 3 files) 0 B / 200.41 MB                                                                                     
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/janweinstock/or1kmvp.git/info/lfs'

Can you please make a release so I can get the latest versions including the linux image. Tried to use the one from release 1.4 but it can not use that either.

BEst Regards
Håkan

**Comment by janweinstock** [comment]
Hi Håkan,

I have fixed this issue in 2afd479.  Hope this helps!
