### ISSUE TITLE
Assistance Needed: Enabling Networking Support for or1kmvp Simulator.. 

### ISSUE THREAD

**Issue by durga-b-r** [janweinstock/or1kmvp#3]
I am currently engaged in implementing or1kmvp and encountered an obstacle during the process of enabling networking support. Specifically, when attempting to connect the running simulator from the host, authentication credentials are requested, hindering progress. Could you kindly provide the necessary login details for the simulator to facilitate the activation of network support? Your assistance in resolving this matter would be greatly appreciated.

**Comment by janweinstock** [comment]
If you are referring to the terminal login, just enter `root` and hit return.

**Comment by durga-b-r** [comment]
I am facing difficulty entering the password when attempting to establish an SSH connection (ssh root@10.0.0.2) to the running simulator from the host. Despite following all the prescribed steps to create a TAP interface with default values, the TAP interface was successfully created but encountered difficulties establishing connections within the virtual platform. Kindly guide me on the same

**Comment by janweinstock** [comment]
The simulator uses the SLIRP network backend by default; to use the TAP network backend, execute the following:
```
./bin/or1kmvp -f config/up.cfg -c system.bridge.backends=tap:0
```

Afterwards you can configure your network interface in the simulator:
```
ifconfig eth0 10.0.0.2
```

Then you should be able to ping the simulator from the host (`ping 10.0.0.2`) or the host from the simulator (`ping 10.0.0.1`). SSH connections are currently not possible as `sshd` and `telnetd` have been removed from the rootfs due to file size limitations. To achieve this, you should build your own rootfs.

**Comment by durga-b-r** [comment]
Thank you for your prompt reply. 
I have converted the 'sample.c' file, which is a C file designed to print "hello world," into an ELF executable using or1k-elf-gcc. However, I am encountering a segmentation fault when attempting to execute this executable file in the simulator. I would greatly appreciate your assistance in troubleshooting and resolving this issue.

![ss](https://github.com/janweinstock/or1kmvp/assets/62275615/83bad41b-63ba-48f1-907f-a59f0b036522)

**Comment by durga-b-r** [comment]
I am interested to build my own rootfs to establish SSH connections. Could you please provide guidance on how to accomplish this?
Also while endeavoring to transfer the elf file of a .c file for printing "hello world" to the root directory of the VP, I have encountered a challenge due to insufficient available space. I kindly seek your guidance on increasing the available space to facilitate the copying and execution of the elf file.

**Comment by janweinstock** [comment]
I suggest using [buildroot](https://buildroot.org) for building your own rootfs. This will also provide you with a compiler/sdk to build your own linux programs.

Closing this issue since it is out of scope for or1kmvp.

**Comment by durga-b-r** [comment]
I am a beginner. I have built the rootfs file system as an ext2 format. Can you please provide more information on how you generated the sdcard0.gpt file.
